<?php

use PHPMailer\PHPMailer\PHPMailer;

//create a new PHPMailer object
$mail = new PHPMailer();
// SMTP configuration
$mail->isSMTP();
$mail->Host = 'smtp.mailtrap.io';
$mail->SMTPAuth = true;
$mail->Username = '896e9a4a931b8f'; //paste one generated by Mailtrap
$mail->Password = '0b010f2963d2c8'; //paste one generated by Mailtrap
$mail->SMTPSecure = 'tls';
$mail->Port = 2525;
//Specify PHPMailer headers
try {
    $mail->setFrom('carolgitonga45@gmail.com', 'Carol Koi');
    //Specify the recipient of your message
    $mail->addReplyTo('carolgitonga45@gmail.com', 'Carol Koi');
    $mail->addAddress('gitongacarol11@gmail.com', 'Caroline');
    $mail->addCC('cc1@example.com', 'Elena');
    $mail->addBCC('bcc1@example.com', 'Alex');
} catch (\PHPMailer\PHPMailer\Exception $e) {
}
$mail->Subject = 'Account Activation Required';
//set the email format to HTML with isHTML(true) property
$mail->isHTML(true);

$mailContent = "<h1>Activate your Account</h1>
    <p>Please click the following link to activate your account.</p>";
$mail->Body = $mailContent;

try {
    if ($mail->send()) {
        echo 'Message has been sent';
    } else {
        echo 'Message could not be sent.';
        echo 'Mailer Error: ' . $mail->ErrorInfo;
    }
} catch (\PHPMailer\PHPMailer\Exception $e) {
}

